version: "3.8"
services:
  db:
    image: mysql
    ports:
      - 3306:3306
    volumes:
      - mysql:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: admin12345
#      MYSQL_DATABASE: flash-dash
      MYSQL_DATABASE: twixAxeShop
#      MYSQL_USER: root
      MYSQL_PASSWORD: admin12345

# If there is problem with connecting to mssql database here is possible solution
# Go to exec in mysql database container
# Use commands below:
#  CREATE USER 'root'@'%' IDENTIFIED BY 'admin12345';
#  GRANT ALL PRIVILEGES ON *.* TO 'root'@'%'

#  backend:
#    build: .
#    ports:
#      - 8080:8080
#    environment:
#      - JWT_KEY=sQF1C+qQJpmV9A/M8/LPd5esayq2dpG/cD0MCEwJZjM
#      - DB_HOST=jdbc:mysql://db:3306/twixAxeShop?allowPublicKeyRetrieval=true&useSSL=false&serverTimezone=UTC&useLegacyDatetimeCode=false
#      - DB_USERNAME=root
#      - DB_PASSWORD=admin12345
#    depends_on:
#      - db

volumes:
  mysql:
